services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "aerich init-db || echo 'Database already initialized'; aerich upgrade"
    env_file:
      - .env
    # networks:
    #   - backend_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9100:9100"
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: /bin/bash -c "while ! nc -z $POSTGRES_HOST $POSTGRES_PORT; do sleep 1; done; python -m uvicorn back.app:app --host 0.0.0.0 --port 9100 --workers 2 --limit-max-requests 10000"
    env_file:
      - .env
    # networks:
    #   - backend_network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python bot/bot.py
    depends_on:
      backend:
        condition: service_started
    env_file:
      - .env
#     networks:
#       - backend_network

# networks:
#   backend_network:
#     driver: bridge
