version: "3.8"

services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "aerich init-db || echo 'Database already initialized'; aerich upgrade"
    environment:
      - POSTGRES_USER=gen_user
      - POSTGRES_PASSWORD=q1q1q1q1
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=213.109.204.88
      - POSTGRES_DB=p2p-database
    networks:
      - backend_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9100:9100"
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: /bin/bash -c "while ! nc -z 213.109.204.88 5432; do sleep 1; done; python -m uvicorn back.main:app --host 0.0.0.0 --port 9100 --workers 2 --limit-max-requests 10000"
    environment:
      - TORTOISE_ORM=back.main.TORTOISE_ORM
      - DATABASE_URL=postgres://gen_user:q1q1q1q1@213.109.204.88:5432/p2p-database
    networks:
      - backend_network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python bot/bot.py
    depends_on:
      backend:
        condition: service_started
    environment:
      - BOT_API_KEY=${BOT_TOKEN}
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
