version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - TORTOISE_ORM=back.main.TORTOISE_ORM

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "bot/bot.py"]
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: gamaun
      POSTGRES_PASSWORD: q1q1q1q1
      POSTGRES_DB: metrics_db
    ports:
      - "5432:5432"
